name: e_commerce_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  dartz: ^0.10.1
  dots_indicator: ^4.0.1
  equatable: ^2.0.7
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.1.2
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  flutter_svg_provider: ^1.0.7
  font_awesome_flutter: ^10.10.0
  get_it: ^8.2.0
  git: ^2.3.1
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.2.1
  iconsax: ^0.0.8
  lucide_icons: ^0.257.0
  modal_progress_hud_nsn: ^0.5.1
  page_transition: ^2.1.0
  provider: ^6.1.5+1
  remixicon: ^1.4.1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_images.dart
  field_prefix: null

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
