// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD16GQsDl13AmpyX9gTUsS3mUPfXFb92Ec',
    appId: '1:865316312109:web:302e4962fa0b4858ffd4a4',
    messagingSenderId: '865316312109',
    projectId: 'fruits-hub-ae213',
    authDomain: 'fruits-hub-ae213.firebaseapp.com',
    storageBucket: 'fruits-hub-ae213.firebasestorage.app',
    measurementId: 'G-7E354SQNLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCohl6C0w2WcihB7keoFu_GKCsonbDgRSk',
    appId: '1:865316312109:android:99e8e76e901bf587ffd4a4',
    messagingSenderId: '865316312109',
    projectId: 'fruits-hub-ae213',
    storageBucket: 'fruits-hub-ae213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsp7phJnVehW2lgqS3iXm4fblljokTprs',
    appId: '1:865316312109:ios:83b0078d3c2e8e78ffd4a4',
    messagingSenderId: '865316312109',
    projectId: 'fruits-hub-ae213',
    storageBucket: 'fruits-hub-ae213.firebasestorage.app',
    iosClientId: '865316312109-3docbr7084ek0kpohsl505ik821l3g0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsp7phJnVehW2lgqS3iXm4fblljokTprs',
    appId: '1:865316312109:ios:83b0078d3c2e8e78ffd4a4',
    messagingSenderId: '865316312109',
    projectId: 'fruits-hub-ae213',
    storageBucket: 'fruits-hub-ae213.firebasestorage.app',
    iosClientId: '865316312109-3docbr7084ek0kpohsl505ik821l3g0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD16GQsDl13AmpyX9gTUsS3mUPfXFb92Ec',
    appId: '1:865316312109:web:f40b576cd7016b03ffd4a4',
    messagingSenderId: '865316312109',
    projectId: 'fruits-hub-ae213',
    authDomain: 'fruits-hub-ae213.firebaseapp.com',
    storageBucket: 'fruits-hub-ae213.firebasestorage.app',
    measurementId: 'G-8G3ZMHP86T',
  );
}
